### ISSUE TITLE
Toy example to show the use of NN-smoothing

### ISSUE THREAD

**Issue by redst4r** [IlyaLab/gssnng#19]
We should think of a  toy example that showcases the usefulness of smoothing the epxression data. Haven't found a good one yer

**Comment by Gibbsdavidl** [comment]
Now we can turn off smoothing with smooth_mode="off", and we can use the new method "geneset_overlap" to compare the overlap (or scoring) with and without smoothing.

**Comment by Gibbsdavidl** [comment]
This was addressed in the paper.
